# Generated by Django 3.0.2 on 2021-01-12 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name_Viet', models.CharField(max_length=200)),
                ('bank_name_En', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('modified', models.DateField(blank=True, null=True)),
                ('created', models.DateField()),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBSystem.UserType')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False)),
                ('wether_complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBSystem.CustomerList')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_branch_name', models.CharField(max_length=200)),
                ('bank_address', models.TextField()),
                ('banker_1', models.CharField(max_length=200)),
                ('banker_2', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(max_length=200)),
                ('bank_account_holder', models.CharField(max_length=200)),
                ('bank_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBSystem.BankAccounts')),
                ('banks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBSystem.Banks')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBSystem.UserInfo')),
            ],
        ),
    ]
