# Generated by Django 3.0.2 on 2021-03-04 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PBSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
