# Generated by Django 3.0.2 on 2021-01-12 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PBSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountdata',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='modified',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
