# Generated by Django 3.0.2 on 2021-04-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccounts',
            old_name='bank_account',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='bankaccounts',
            old_name='bank_accountID',
            new_name='customer_name',
        ),
    ]
