# Generated by Django 3.0.2 on 2021-01-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSystem', '0002_auto_20210112_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdata',
            name='match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccountdata',
            name='wether_complete',
            field=models.BooleanField(default=False),
        ),
    ]
